### ISSUE TITLE
Backend Setup

### ISSUE THREAD

**Issue by raysarinas** [CMPUT404W21T02/group-project#1]
### Related User Stories
**29 - As a server admin, I want a restful interface for most operations**

### Description / Notes
- Base code for everyone to work off of
- Justin and Vinny to do

### Tasks
- [x] All models created
- [x] Author endpoints + tests
- [x] Follower endpoints + tests
- [x] Post endpoints + tests
- [x] Comment endpoints + tests
- [x] Like endpoints + tests
- [x] Inbox endpoints + tests

**Comment by Vikas12911** [comment]
Hi,i would like to work on thsi issue.

**Comment by jmmxp** [comment]
We've finished all the endpoints and models. One issue that we'll have to revisit is the models not being 100% accurate, depending on how Dr. Hindle wants things to be implemented. These fixes can be added on a case-by-case basis later.

There are endpoint tests for every single endpoint, but no models tests as of now. We will probably need to clarify what is exactly needed in model tests.
