### ISSUE TITLE
Edit Public Posts

### ISSUE THREAD

**Issue by raysarinas** [CMPUT404W21T02/group-project#11]
### Related User Stories
**2. As an author I want to edit public posts.**

### Description / Notes
- POST update the post (must be authenticated)
- Should include tests for simple plain text and CommonMark posts (not for any other type)
- Need to discuss authentication aspect
- This task could be limited to editing just text posts and editing image posts could be separated into a separate issue if necessary

### Tasks
- [ ] POST updating a public post
- [ ] Test POST updating a public text post
- [ ] Test POST updating a CommonMark text post
