### ISSUE TITLE
UI for Editing Posts

### ISSUE THREAD

**Issue by raysarinas** [CMPUT404W21T02/group-project#12]
### Related User Stories
**2. As an author I want to edit public posts.**

### Description / Notes
- UI for editing a public post (POST update the post)
- Need to discuss authentication aspect
- This task could be limited to editing just text posts and editing image posts could be separated into a separate issue if necessary

### Tasks
- [ ] UI for editing a post
- [ ] Test UI
- [ ] Test being able to send a POST request to update
- [ ] Test being able to receiving a response
