### ISSUE TITLE
UI for Creating and Editing Image Posts

### ISSUE THREAD

**Issue by raysarinas** [CMPUT404W21T02/group-project#14]
### Related User Stories
**1. As an author I want to make public posts.
3. As an author, posts I create can link to images.
4. As an author, posts I create can be images.**

### Description / Notes
- Test UI for creating and editing image or image link posts

### Tasks
- [ ] Rerun UI tests for creating posts
- [ ] Rerun UI tests for editing posts
- [ ] Modify tests if necessary
