### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by raysarinas** [CMPUT404W21T02/group-project#5]
### Related User Stories
**13. As a server admin, I want to host multiple authors on my server**
**27. As a server admin, I want to OPTIONALLY be able allow users to sign up but require my OK to finally be on my server**

### Description / Notes
- User should be able to register/create an account - need to discuss authentication (whether or not we care)
- Backend should receive a POST request to "update" a profile on registration and then add user to the database - need to discuss if this is the way to go
- Need to discuss what it means but requiring an "OK" from a server admin - probably related to authentication
- Discuss details of test for UI? Testing the backend/database stuff should be easy and could be done separately
- Discuss whether or not how to proceed with testing with PostgreSQL - will we need it set up first?

### Tasks
- [ ] Create UI for User Registration
- [ ] Process user registration on backend
- [ ] Test POST request
