### ISSUE TITLE
UI for User Profile Stream

### ISSUE THREAD

**Issue by raysarinas** [CMPUT404W21T02/group-project#73]
### Related User Stories
**16. As an author, I want to post posts to my "stream."
37. As an author, I should be able to browse the public posts of everyone.**

### Description / Notes
Chris already has some code in for lists of posts, we may just need to extend what is already in the code to have this be specific to viewing our own profile, and other user profiles (with just their public posts).

### Tasks
- [x] Rerun and modify tests if necessary
- [x] UI for user profile streams
- [x] Streams only contain public posts for other profiles
