### ISSUE TITLE
Make and Get Public Text Posts

### ISSUE THREAD

**Issue by raysarinas** [CMPUT404W21T02/group-project#8]
### Related User Stories
**1. As an author I want to make public posts.
10. As an author, posts I make can be in simple plain text
11. As an author, posts I make can be in CommonMark**

### Description / Notes
- POST create a new post and generate a post_id
- GET get the public post
- PUT create a post with given post_id
- Should include tests for simple plain text and CommonMark posts (not for any other type)

### Tasks
- [ ] POST creates a new post and generates a post_id
- [ ] GET get the public post
- [ ] Test POST creates a new post
- [ ] Test POST generates a post_id
- [ ] Test GET public post
- [ ] Test PUT create a post with given post_id
