### ISSUE TITLE
UI for Creating (Text) Posts

### ISSUE THREAD

**Issue by raysarinas** [CMPUT404W21T02/group-project#9]
### Related User Stories
**1. As an author I want to make public posts.
10. As an author, posts I make can be in simple plain text
11. As an author, posts I make can be in CommonMark
25. As an author, I want to be able to use my web-browser to author my posts**

### Description / Notes
- UI for making a new post (POST create a new post but generate a post_id and PUT create a post with a given post_id)
- This task could be limited to creating just text posts and creating image posts could be separated into a separate issue if necessary

```
URL: ://service/author/{AUTHOR_ID}/posts/{POST_ID}
PUT create a post with that post_id

Creation URL ://service/author/{AUTHOR_ID}/posts/
POST create a new post but generate a post_id
```

### Tasks
- [ ] UI for a new post
- [ ] Test UI
- [ ] Test being able to send a POST request
- [ ] Test receiving a response to a POST request?
- [ ] Test being able to send a PUT request with a given post_id
- [ ] Test receiving a response to a PUT request
